apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra-services
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  type: ClusterIP

# redis.infra-services.svc.cluster.local:6379