apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: infra-services
spec:
  clusterIP: None
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

# postgres-db-service.infra-services.svc.cluster.local:5432