services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: micronotes
      POSTGRES_PASSWORD: cantremember
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    image: auth-service-image
    build: ./services/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
    env_file:
      - ./services/auth-service/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
