apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
  namespace: app-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:
      containers:
        - name: notes-service
          image: ijas9118/micronotes-notes-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: notes-config
            - secretRef:
                name: notes-secret
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
