apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: infra-services
spec:
  ports:
    - port: 9092
      name: plaintext
    - port: 9093
      name: controller
  clusterIP: None
  selector:
    app: kafka

# KAFKA_BROKER=kafka.infra-services.svc.cluster.local:9092