apiVersion: v1
kind: Service
metadata:
  name: notes-service
  namespace: app-services
spec:
  selector:
    app: notes-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 32003
  type: NodePort
